### PR TITLE
Update c-icap to 0.5.8 & c-icap-modules to 0.5.5.

### PR DESCRIPTION
**Pull request by Gacko**
Also format c-icap-modules.spec and include new clamav_mod.conf.

### CODE REVIEW

**Comment by gsanchietti** [comment]
Hi Gacko,
thank you for the PR :) But I don't get why it's needed.

What are you trying to achieve?

**Comment by Gacko** [comment]
I was looking for SPECs for c-icap and yours looked quite good despite the fact the used versions were a little older. Since changing the versions required some extra work (adding new module files, removing additional files after build) I propose the changes I made to everyone else finding your work.

Unfortunately it seems like I forgot to create a separate branch and all my private improvements not required to get things running with latest version also got into this PR. So if you're still interested I'll create an extra branch and a new PR for only changing versions.

**Comment by Gacko** [comment]
... yeah, nvm. Just took a look into your other repositories and understood you're probably not interested in contribution since c-icap is just one part of a whole and might break if simply updated.

**Comment by gsanchietti** [comment]
You've got the point: c-icap is just a little part of the system.
For now, we have no plan to do another c-icap release, but thank you for the work we will use it if a new update is needed!

**Pull request closed without merging**
